/** AUTO-GENERATED by scripts/import-open-drug-products.mjs — do not edit.
 * Finished-drug identity (openFDA NDC + multi-region + CN brands). Generated: 2026-09-08T09:45:05.040Z
 * Count: 7645 provenance: who-eml-curated+ema-curated+mhra-curated+pmda-curated+cn-brand-curated+openfda-ndc
 */
import data from "./openDrugProducts.generated.json";

export type OpenDrugProductRecord = {
  id: string;
  brandName: string;
  genericName: string;
  inn?: string;
  strength?: string;
  dosageForm?: string;
  route?: string;
  productNdc?: string;
  countryTags: string[];
  regionTags: string[];
  unii?: string;
  parentUnii?: string;
  parentSubstanceId?: string;
  labelerName?: string;
  productType?: string;
  marketingCategory?: string;
  synonyms: string[];
  provenance: string;
  source: "openfda" | "open";
};

export const OPEN_DRUG_PRODUCTS_META = {
  "generatedAt": "2026-09-08T09:45:05.040Z",
  "count": 7645,
  "provenance": "who-eml-curated+ema-curated+mhra-curated+pmda-curated+cn-brand-curated+openfda-ndc",
  "limit": 4000,
  "files": [
    "drug-ndc-0001-of-0001.json",
    "global-products-seed.json"
  ],
  "regionCounts": {
    "WHO": 552,
    "EU": 767,
    "UK": 775,
    "JP": 747,
    "CN": 804,
    "US": 4000
  },
  "cnBrandAliases": 358,
  "expectedFullScale": "100k+ openFDA NDC + multi-region curated seeds; git keeps high-value merged identity seed"
} as const;

export const openDrugProducts = data as OpenDrugProductRecord[];
