/** AUTO-GENERATED by scripts/import-open-drug-products.mjs — do not edit.
 * Finished-drug identity (openFDA NDC + multi-region + CN brands). Generated: 2026-09-09T01:26:36.415Z
 * Count: 11005 provenance: who-eml-curated+ema-curated+mhra-curated+pmda-curated+cn-brand-curated+openfda-ndc
 */
import data from "./openDrugProducts.generated.json";

export type OpenDrugProductRecord = {
  id: string;
  brandName: string;
  genericName: string;
  inn?: string;
  strength?: string;
  dosageForm?: string;
  route?: string;
  productNdc?: string;
  countryTags: string[];
  regionTags: string[];
  unii?: string;
  parentUnii?: string;
  parentSubstanceId?: string;
  labelerName?: string;
  productType?: string;
  marketingCategory?: string;
  synonyms: string[];
  provenance: string;
  source: "openfda" | "open";
};

export const OPEN_DRUG_PRODUCTS_META = {
  "generatedAt": "2026-09-09T01:26:36.415Z",
  "count": 11005,
  "provenance": "who-eml-curated+ema-curated+mhra-curated+pmda-curated+cn-brand-curated+openfda-ndc",
  "limit": 6000,
  "files": [
    "drug-ndc-0001-of-0001.json",
    "global-products-seed.json"
  ],
  "regionCounts": {
    "WHO": 601,
    "EU": 870,
    "UK": 883,
    "JP": 807,
    "CN": 1844,
    "US": 6000
  },
  "cnBrandAliases": 632,
  "expectedFullScale": "100k+ openFDA NDC + multi-region curated seeds; git keeps high-value merged identity seed"
} as const;

export const openDrugProducts = data as OpenDrugProductRecord[];
