/** AUTO-GENERATED by scripts/import-open-substances.mjs — do not edit.
 * Identity layer only. Generated: 2026-09-09T01:26:29.799Z
 * Count: 7617 provenance: ndc
 */
import data from "./openSubstances.generated.json";

export type OpenSubstanceRecord = {
  id: string;
  nameEn: string;
  nameZh?: string;
  cas?: string;
  unii?: string;
  synonyms: string[];
  source: "unii" | "open" | "ndc";
  provenance: "gsrs" | "seed" | "ndc";
};

export const OPEN_SUBSTANCES_META = {
  "generatedAt": "2026-09-09T01:26:29.799Z",
  "count": 7617,
  "provenance": "ndc",
  "limit": 12000,
  "requireCas": false,
  "stream": true,
  "files": [
    "ndc-derived-substances.csv",
    "api-extra-seed.csv"
  ],
  "expectedFullScale": "100k-200k+ UNII / NDC-derived rows before LIMIT; default LIMIT 12000 for local; git keeps high-value seed"
} as const;

export const openSubstances = data as OpenSubstanceRecord[];
